There is a lot more that you can do with outputs (such as including interactive outputs)
with your book. For more information about this, see [the Jupyter Book documentation](https://jupyterbook.org)

# Tugas 1

Tugas Menugukur Jarak (dissimiliarity) menggunakan python
1. ambil data dari keggle/github
2. ukur jarak

d(1,2), d(1,2) d(1,4) objek dari data tersebut

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/DiahDSyntia/Data-Mining/main/biopics.csv", encoding = 'unicode_escape', engine ='python')

In [3]:
data

,title,site,country,year_release,box_office,director,number_of_subjects,subject,type_of_subject,race_known,subject_race,person_of_color,subject_sex,lead_actor_actress
0,10 Rillington Place,http://www.imdb.com/title/tt0066730/,UK,1971,-,Richard Fleischer,1,John Christie,Criminal,Unknown,NaN,0,Male,Richard Attenborough
1,12 Years a Slave,http://www.imdb.com/title/tt2024544/,US/UK,2013,$56.7M,Steve McQueen,1,Solomon Northup,Other,Known,African American,1,Male,Chiwetel Ejiofor
2,127 Hours,http://www.imdb.com/title/tt1542344/,US/UK,2010,$18.3M,Danny Boyle,1,Aron Ralston,Athlete,Unknown,NaN,0,Male,James Franco
3,1987,http://www.imdb.com/title/tt2833074/,Canada,2014,-,Ricardo Trogi,1,Ricardo Trogi,Other,Known,White,0,Male,Jean-Carl Boucher
4,20 Dates,http://www.imdb.com/title/tt0138987/,US,1998,$537K,Myles Berkowitz,1,Myles Berkowitz,Other,Unknown,NaN,0,Male,Myles Berkowitz
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
756,Young Man with a Horn,http://www.imdb.com/title/tt0043153/,US,1950,-,Michael Curtiz,1,Bix Beiderbecke,Musician,Known,White,0,Male,Kirk Douglas
757,Young Mr. Lincoln,http://www.imdb.com/title/tt0032155/,US,1939,-,John Ford,1,Abraham Lincoln,World leader,Known,White,0,Male,Henry Fonda
758,Young Tom Edison,http://www.imdb.com/title/tt0033289/,US,1940,-,Norman Taurog,1,Thomas Edison,Other,Known,White,0,Male,Mickey Rooney
759,Young Winston,http://www.imdb.com/title/tt0069528/,US,1972,-,Richard Attenborough,1,Winston Churchill,World leader,Known,White,0,Male,Simon Ward
760,Your Cheatin' Heart,http://www.imdb.com/title/tt0058765/,US,1964,-,Gene Nelson,1,Hank Williams,Musician,Unknown,NaN,0,Male,George Hamilton

In [4]:
number_of_columns = data.shape[1]

In [5]:
pd.set_option('display.max_columns', number_of_columns)
pd.set_option('display.max_rows', number_of_columns)

In [6]:
data.columns

Index(['title', 'site', 'country', 'year_release', 'box_office', 'director',
       'number_of_subjects', 'subject', 'type_of_subject', 'race_known',
       'subject_race', 'person_of_color', 'subject_sex', 'lead_actor_actress'],
      dtype='object')

## Categorical/nominal Features
*   race_known
*   person_of_color

In [7]:
data[["title","race_known", "person_of_color"]].head(15)

                    title race_known  person_of_color
0     10 Rillington Place    Unknown                0
1        12 Years a Slave      Known                1
2               127 Hours    Unknown                0
3                    1987      Known                0
4                20 Dates    Unknown                0
..                    ...        ...              ...
10  84 Charing Cross Road    Unknown                0
11       A Beautiful Mind    Unknown                0
12     A Dangerous Method      Known                0
13     A Dangerous Method      Known                0
14     A Dangerous Method      Known                0

[15 rows x 3 columns]

## Change Values to 1/0
- Take all values of 'race_known' series


*   if values is known change to 1
*   if values is unknown change to 0

In [8]:
# race_known code
code_race_known_for_known = "Known"
code_race_known_for_unknown = "Unknown"

# binary value
value_of_one = 1
value_of_zero = 0

def change_code_race_known_to_biner(race_known):
    return value_of_one if race_known == code_race_known_for_unknown else value_of_zero

In [9]:
# Update all values of 'race_known' series
data["race_known"] = data["race_known"].apply(change_code_race_known_to_biner)

In [10]:
data[["title","race_known", "person_of_color"]].head(7)

                  title  race_known  person_of_color
0   10 Rillington Place           1                0
1      12 Years a Slave           0                1
2             127 Hours           1                0
3                  1987           0                0
4              20 Dates           1                0
5                    21           0                1
6  24 Hour Party People           0                0

In [11]:
# CONSTAN VARIABLE
DECREMENT_BY_ONE = 1
INCREMENT_BY_ONE = 1

CONTINGENCY_TABLE_VALUE = {
    "q" : (1,1),
    "r" : (1,0),
    "s" : (0,1),
    "t" : (0,0),
}

In [12]:
def get_series(df, idx, series):
    return df.loc[(idx), series]

In [13]:
def get_dissimilarity_dataset(df, series_index = [], series = []):
    first_series = get_series(df, series_index[0], series)
    second_series = get_series(df, series_index[1], series)
    dataset = pd.concat([first_series,second_series],axis=1)
    return dataset.T

In [14]:
get_dissimilarity_dataset(data, [1,2], ["race_known", "person_of_color"]).T

                 1  2
race_known       0  1
person_of_color  1  0

In [15]:
data.loc[0:5, ["race_known", "person_of_color"]]

   race_known  person_of_color
0           1                0
1           0                1
2           1                0
3           0                0
4           1                0
5           0                1

In [16]:
def count_contingency_value(df, start_index = 0, last_index = 1):

    CONTINGENCY_VALUE = {
        "q" : 0,
        "r" : 0,
        "s" : 0,
        "t" : 0,
    }

    column_range = df.shape[1]

    for column in range(column_range):
        for value in CONTINGENCY_TABLE_VALUE:
            item = list((tuple(df.loc[(start_index):(last_index), df.columns[column]]) == CONTINGENCY_TABLE_VALUE[value], value))
            if item[0] == True:
                if item[1] == "q":
                    CONTINGENCY_VALUE["q"] += 1
                if item[1] == "r":
                    CONTINGENCY_VALUE["r"] += 1
                if item[1] == "s":
                    CONTINGENCY_VALUE["s"] += 1
                if item[1] == "t":
                    CONTINGENCY_VALUE["t"] += 1

    return CONTINGENCY_VALUE

In [17]:
# d(1,2)
data_1_2 = get_dissimilarity_dataset(data, [1,2], ["race_known", "person_of_color"])

In [18]:
c_d_1_2 = count_contingency_value(data_1_2, 1, 2)

In [19]:
# d(1,3)
data_1_3 = get_dissimilarity_dataset(data, [1,3], ["race_known", "person_of_color"])

In [20]:
c_d_1_3 = count_contingency_value(data_1_3, 1, 3)

In [21]:
# d(1,4)
data_1_4 = get_dissimilarity_dataset(data, [1,4], ["race_known", "person_of_color"])

In [22]:
c_data_1_4 = count_contingency_value(data_1_4, 1, 4)

In [23]:
# d(1,5)
data_1_5 = get_dissimilarity_dataset(data, [1,5], ["race_known", "person_of_color"])

In [24]:
c_data_1_5 = count_contingency_value(data_1_5, 1, 5)

### Dissimilarity Binary Assymetric Value Formula

$$
\frac{r + s}{q + r + s}\
$$

In [25]:
def measure_dissimilarity_binary_value_assymetric_distance(contingency_value):

    return (contingency_value["r"] + contingency_value["s"]) / (contingency_value["q"] + contingency_value["r"] + contingency_value["s"])

In [38]:
d_1_2 = measure_dissimilarity_binary_value_assymetric_distance(c_d_1_2)
d_1_3 = measure_dissimilarity_binary_value_assymetric_distance(c_d_1_2)
d_1_4 = measure_dissimilarity_binary_value_assymetric_distance(c_d_1_2)
d_1_5 = measure_dissimilarity_binary_value_assymetric_distance(c_d_1_2)
d_1_6 = measure_dissimilarity_binary_value_assymetric_distance(c_d_1_2)

In [32]:
d_1_2

1.0

In [33]:
d_1_3

1.0

In [34]:
d_1_4

1.0

In [35]:
d_1_5

1.0

In [36]:
d_1_6

1.0